[tool.poetry]
name = "app-bootcamp"
version = "0.1.0"
description = ""
authors = ["Pau Rullan <prullanferragut@twilio.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.0.0"
python-decouple = "^3.4"
twilio = "^6.60.0"
replit = "^3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.poetry.dependencies]
flask = "^2.0.0"
replit = "^3.1.0"